
error_codes = {
    0x0: 'NO_ERROR',
    0x1: 'PROTOCOL_ERROR',
    0x2: 'INTERNAL_ERROR',
    0x3: 'FLOW_CONTROL_ERROR',
    0x4: 'SETTINGS_TIMEOUT',
    0x5: 'STREAM_CLOSED',
    0x6: 'FRAME_SIZE_ERROR',
    0x7: 'REFUSED_STREAM',
    0x8: 'CANCEL',
    0x9: 'COMPRESSION_ERROR',
    0xa: 'CONNECT_ERROR',
    0xb: 'ENHANCE_YOUR_CALM',
    0xc: 'INADEQUATE_SECURITY',
    0xd: 'HTTP_1_1_REQUIRED',
}
